################
##
## @description Execute a simulation of the reproducibility model
##
## @param replications Number of replications to run
## @param timesteps    Length of each simulation
## @param models       All possible linear regression models
## @param k            Number of factors
## @param tModel       String representing the True model
## @param nRey         Number of agents of type Rey
## @param nRob         Number of agents of type Rob
## @param nCara        Number of agents of type Cara
## @param nNell        Number of agents of type Nell
## @param betas        Betas weight
## @param sampleSize   Sample size
## @param correlation  Sample correlation
## @param sigma        Data error variance
## @param modelCompare Type of model comparison
## @param inputDir     Data input directory
## @param outputDir    Data output directory
## @param outputFile   Raw output file name
## @param paramFile    Parameter output file name
## @param verbose      Verbose model (Enabled TRUE)
## @param ndec         Number of decimal places
## @param seeds        Vector of seeds
##
## @return None
##
## @lastChange 2018-02-28
##
## @changes
##   Included BIC model comparison (02/28/2018)
##   Included the parameter file output (06/17/2017)
##   Included the Beta1 True output (06/08/2017)
##   Changed the Distance Calculation (12/07/2016)
##   Y generated using random Betas assuming error is 1 - sigma (11/13/2016) 
##   Added Beta1 Standard Error (11/07/2016)
##   Round output values number of decimal places (11/07/2016)
##   Fixed the statistics output information (11/01/2016)
##   Normalized data generated by generateXSet and generateY (10/17/2016)
##   Created getPredictors and getBetas (10/10/2016)
##   Record whether or not RAY replicated the previous result (10/10/2016)
##   Fixed RAY reproducibility (10/10/2016)
##   Fixed so the model comparison uses the same data set (09/20/2016)
##   Included Adjusted R Square (09/20/2016)
##   Changed RAY to reproduce the previous models (09/11/2016)
##   Record additional models data (08/27/2016)
##   Run multiple replications (08/24/2016)
##   Added random seed control (08/24/2016)
##   Fix the generateModels function (08/02/2016)
##   Add new outputs Beta1, RSQ, T-statistics, AIC (06/24/16)
##   Determine the number of predictors of all model (06/24/16)
##   Adjust p-value -> t-statistics (06/24/16)
##   Similar models adding interaction for BOB (X1 necessary) (06/24/16)
##   searchModel function needs review (06/23/16)
##   Consider interactions in model expectation calculation (06/22/16)
##   Change nBob to nCara, nNel to nNell, nRay to nRey (10/16/2017)
##
################
simulator <- function(replications, timesteps, models, k, tModel,
    nRey, nRob, nCara, nNell, weights, sampleSize, correlation, sigma,
    modelCompare, inputDir, outputDir, outputFile, paramFile,
    verbose, ndec, seeds){
  
  
  ###################
  ## REPLICA SIMULATION
  ###################
  parameters <- list()
  for(replica in 1:replications){
    set.seed(seeds[replica])
    
    ## Generate Xset and deterministic value of the linear regression
    Xset <- generateXSet(sampleSize, k, correlation)
    tModelBetas <- getBetas(tModel, weights, sigma)
    deterministic <- calculateDet(tModel, Xset, weights, tModelBetas)
    
    ## Select randomly Global Model and previous Global Model
    gModel <- models[[as.integer(runif(1, min=1, max=length(models) + 1))]]
    
    model1 <- models[[as.integer(runif(1, min=1, max=length(models) + 1))]]
    model2 <- gModel
    
    ## Initialize agents
    N <- c(rep(REY, nRey), rep(ROB, nRob), rep(CARA, nCara), rep(NELL, nNell))
    N <- N[shuffle(length(N))]
    
    agentTypes <- N[as.integer(runif(timesteps, min=1,
                                     max=(nRey + nRob + nCara + nNell + 1)))]
    
    #######################
    ## OUTPUT PARAMETERS
    #######################
    output <- matrix(data=NA, nrow=timesteps, ncol=O_NUM_FIELDS)
    
    
    #######################
    ## SIMULATION EXECUTION
    #######################
    for(step in 1:timesteps){
      if(verbose){
        print(paste0(replica, " ", step))
      }
      
      ## Select the type of agent
      agentType <- agentTypes[step]
      
      ## Ray (replicator)
      if(agentType == REY){
        if(!compareModels(model2, gModel)){
          model <- model2
        } else {
          model <- model1
        }
        
      ## Rob (robust)
      } else if(agentType == ROB){
        model <- modelSimilarByTerm(gModel, models, mode="random")
        
      ## Bob (robust)
      } else if(agentType == CARA){
        model <- modelSimilarByInteraction(gModel, models, mode="random")
        
      ## Nel (random)
      } else if(agentType == NELL){
        model <- models[[as.integer(runif(1, min=1, max=length(models)+1))]]
      }
      
      model1 <- model
      model2 <- gModel
      
      ## Analyze the Selected Model and Global Model
      Yset <- generateY(deterministic, sigma)
      stat <- analysis(model, gModel, Yset, Xset, weights)
      
      switchModel <- FALSE
      if((modelCompare == TSTATISTICS) &
          (!is.null(stat$model$tstatistics)) &
          (!is.null(stat$gModel$tstatistics)) &
          (!is.na(stat$model$tstatistics)) &
          (!is.na(stat$gModel$tstatistics))){
        if(stat$model$tstatistics > stat$gModel$tstatistics){
          switchModel <- TRUE
        }
      } else if((modelCompare == RSQ) &
          (!is.null(stat$model$rsq)) &
          (!is.null(stat$gModel$rsq)) &
          (!is.na(stat$model$rsq)) &
          (!is.na(stat$gModel$rsq))){
        if(stat$model$rsq > stat$gModel$rsq){
          switchModel <- TRUE
        }
      } else if((modelCompare == AIC) &
          (!is.null(stat$model$aic)) &
          (!is.null(stat$gModel$aic)) &
          (!is.na(stat$model$aic)) &
          (!is.na(stat$gModel$aic))){
        if(stat$model$aic < stat$gModel$aic){
          switchModel <- TRUE
        }
      } else if((modelCompare == BIC) &
          (!is.null(stat$model$bic)) &
          (!is.null(stat$gModel$bic)) &
          (!is.na(stat$model$bic)) &
          (!is.na(stat$gModel$bic))){
        if(stat$model$bic < stat$gModel$bic){
          switchModel <- TRUE
        }
      } else if((modelCompare == ARSQ) &
          (!is.null(stat$model$arsq)) &
          (!is.null(stat$gModel$arsq)) &
          (!is.na(stat$model$arsq)) &
          (!is.na(stat$gModel$arsq))){
        if(stat$model$arsq > stat$gModel$arsq){
          switchModel <- TRUE
        }
      }
      
      initGModel <- gModel
      initGModelStat <- stat$gModel
      
      replicated <- 0
      if(switchModel){
        gModel <- model
        finalGModelStat <- stat$model
        
        ## Not necessary, just to make explicit that in this case REY did not
        ## replicate the previous result
        if(agentType == REY){
          replicated <- 0
        }
      } else {
        finalGModelStat <- stat$gModel
        
        if(agentType == REY){
          replicated <- 1
        }
      }
      
      ## Record output data
      output[step, O_STRATEGY] <- agentType
      output[step, O_SELECTED_MODEL] <- searchModel(model, models)
      output[step, O_SELECTED_TRUE_MODEL] <- as.numeric(compareModels(model, tModel))
      output[step, O_SELECTED_MODEL_DISTANCE] <- round(calculateDistance(tModelBetas, stat$model$betasEst), ndec)
      output[step, O_INITIAL_GLOBAL_MODEL] <- searchModel(initGModel, models)
      output[step, O_INITIAL_GLOBAL_TRUE_MODEL] <- as.numeric(compareModels(initGModel, tModel))
      output[step, O_INITIAL_GLOBAL_MODEL_DISTANCE] <- round(calculateDistance(tModelBetas, initGModelStat$betasEst), ndec)
      output[step, O_FINAL_GLOBAL_MODEL] <- searchModel(gModel, models)
      output[step, O_FINAL_GLOBAL_TRUE_MODEL] <- as.numeric(compareModels(gModel, tModel))
      output[step, O_FINAL_GLOBAL_MODEL_DISTANCE] <- round(calculateDistance(tModelBetas, finalGModelStat$betasEst), ndec)
      output[step, O_NUM_PREDICTORS] <- predictors[[1]][as.numeric(as.character(output[step, O_FINAL_GLOBAL_MODEL]))]
      output[step, O_SAMPLE_SIZE] <- sampleSize
      output[step, O_BETA1_TRUE] <- round(tModelBetas[,2], ndec)
      output[step, O_BETA1_ESTIMATE] <- round(finalGModelStat$betasEst[2], ndec)
      output[step, O_BETA1_ERROR] <- round(finalGModelStat$betasErr[2], ndec)
      output[step, O_TSTATISTICS] <- round(finalGModelStat$tstatistics, ndec)
      output[step, O_RSQ] <- round(finalGModelStat$rsq, ndec)
      output[step, O_ARSQ] <- round(finalGModelStat$arsq, ndec)
      output[step, O_AIC] <- round(finalGModelStat$aic, ndec)
      output[step, O_REPLICATED] <- replicated
      output[step, O_PREDICTORS] <- toString(predictors[[2]][as.numeric(as.character(output[step, O_FINAL_GLOBAL_MODEL]))])
    }
    
    ## Parameter output
    param <- list()
    param[[P_TMODEL]] <- gsub(" ", "", substr(modelToStr(tModel), 5,
            nchar(modelToStr(tModel))), fixed=TRUE)
    param[[P_K]] <- k
    param[[P_SAMPLE_SIZE]] <- sampleSize
    param[[P_SIGMA]] <- sigma
    param[[P_CORRELATION]] <- correlation
    param[[P_AGENT_WEIGHTS]] <- c(nRey, nRob, nCara, nNell) /
        (nRey + nRob + nCara + nNell)
    param[[P_TRUE_BETAS]] <- tModelBetas
    param[[P_XSET]] <- Xset
    parameters[[replica]] <- param
    
    ## Convert output matrix into data table
    output <- data.table(cbind(rep(replica, timesteps), 1:timesteps, output))
    names(output) <- OUTPUT_HEADER
    
    ## Write output data table into a file
    write.table(output, file=paste0(outputDir, "/", outputFile),
        append=ifelse(replica == 1, FALSE, TRUE),
        quote=FALSE, sep=";", row.names=FALSE,
        col.names=ifelse(replica == 1, TRUE, FALSE))
  }
  
  saveRDS(parameters, file=paste0(outputDir, "/", paramFile))
}
